UPDATE: CreateHighlightVideoHandler works
santosfamilyfoundation/TrafficCloud pull request #33
Opened 2017-01-27 23:01 UTC by youralien

2017-01-27 23:11 UTC, jabb1123 approved these changes
Maybe some thought around 'protecting' the threshold for near misses can come later, so no one can make all interactions fall into near-miss clasification

2017-01-27 23:30 UTC, youralien commented
I should make sure the documentation is good, like version numbers.

2017-01-27 23:45 UTC, youralien commented on app/handlers/createHighlightVideo.py
> +            return (500, 'Database file does not exist. Trajectory analysis needs to be called first ')
There should also be a check to see if tables like "interactions" exist.  Right now, this function will error if safety analysis was not called.

2017-01-29 01:30 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +class MyAppBaseHandler(tornado.web.RequestHandler):
This should be in a separate class file.

2017-01-29 01:33 UTC, dcelik requested changes

2017-01-29 01:33 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +class MyAppBaseHandler(tornado.web.RequestHandler):
Move this to a separate class.

2017-01-29 02:03 UTC, jabb1123 submitted a review, later dismissed

2017-01-29 02:03 UTC, jabb1123 commented on app/handlers/createHighlightVideo.py
> +from trafficcloud.video import create_highlight_video, get_framerate
Maybe move video.py into traffic_cloud_utils so that we can get closer to removing trafficcloud folder

2017-01-29 02:03 UTC, jabb1123 commented on app/handlers/createHighlightVideo.py
> +from trafficcloud.app_config import get_project_path, get_project_video_path
app_config.py has since been moved to traffic_cloud_utils. This should now reference the new location, as the old one may become unsupported.

2017-01-29 08:35 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +from trafficcloud.video import create_highlight_video, get_framerate
Fixed.

2017-01-29 08:37 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +from trafficcloud.app_config import get_project_path, get_project_video_path
Fixed.

2017-01-29 08:39 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +            return (500, 'Database file does not exist. Trajectory analysis needs to be called first ')
Adding this as a TO-DO comment. Can be fixed in later branch.

2017-01-29 08:42 UTC, dcelik approved these changes

2017-01-29 08:42 UTC, merged