Config route
santosfamilyfoundation/TrafficCloud pull request #35
Opened 2017-01-28 17:27 UTC by runnersaw

Refactors pm.py for 
- Static methods that take identifiers rather than instance creation
- Updating config
- Only keeping one copy of tracking.cfg

Adds config route that
- Updates tracking.cfg

Untested, and can't really be until Deniz's changes get merged. I need his stuff to be done in order to hook up his uploadVideo and uploadHomography routes to my pm changes.

2017-01-28 17:29 UTC, runnersaw commented on trafficcloud/api.py
> +def uploadVideo(identifier, video_filename):
Note that this will break the current workflow until Deniz's changes get merged.

2017-01-29 01:37 UTC, jabb1123 reviewed
From what I could tell, looked Good. I'm holding off on approval until @dcelik can ok the changes here as well.

2017-01-29 01:53 UTC, jabb1123 requested changes

2017-01-29 01:53 UTC, jabb1123 commented on app/handlers/config.py
> +from trafficcloud.pm import default_config_dict, update_project_config
Perhaps we should move the pm.py file to traffic)cloud)utils now? It seems like we can remove the old trafficcloud folder if we do so.

2017-01-29 01:53 UTC, jabb1123 commented on trafficcloud/api.py
> +def uploadVideo(identifier, video_filename):
Isn't this file fairly superfluous at this point? Why not move all these function under the handlers that call them? Then, in the future, if we need to change them, we can edit the handlers that now have these functions. In addition, we can remove this file, and in turn, this whole trafficcloud folder.

2017-01-29 03:30 UTC, dcelik approved these changes

2017-01-29 03:30 UTC, dcelik commented on app/handlers/config.py
> +from trafficcloud.pm import default_config_dict, update_project_config
this can be done post-merge, during refactoring

2017-01-29 03:30 UTC, dcelik commented on trafficcloud/api.py
> +def uploadVideo(identifier, video_filename):
Why does project wizard no longer generate a uuid?? This identifier creation will be added to UploadVideoHandler.

2017-01-29 03:38 UTC, dcelik requested changes

2017-01-29 03:38 UTC, dcelik commented on trafficcloud/api.py
> +def uploadVideo(identifier, video_filename):
This will require significant changes to uploadVideo handler to function correctly. Will not be merged until my changes can be merged.

2017-01-29 06:08 UTC, merged