Sort and limit highlight video
santosfamilyfoundation/TrafficCloud pull request #61
Opened 2017-02-13 01:08 UTC by runnersaw

Needs to go in after this change:

https://bitbucket.org/santosfamilyfoundation/trafficintelligence/pull-requests/new?source=include-ttc&t=1

2017-02-14 00:06 UTC, dcelik requested changes

2017-02-14 00:06 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +        num_near_misses_to_use = 5
This should be a default argument we pass in so that the user can change the number they want to see, much like num_frames in test_config.

2017-02-14 03:32 UTC, runnersaw commented on app/handlers/createHighlightVideo.py
> +        num_near_misses_to_use = 5
Sure, but we still should discuss a maximum value for this. I'd like to propose a semi-arbitrary 10?

2017-02-14 23:57 UTC, dcelik commented on app/handlers/createHighlightVideo.py
> +        num_near_misses_to_use = 5
That sounds good, I think 10 is a fine number for now.

2017-02-15 17:15 UTC, dcelik approved these changes
Looks good, nice conversion to SQL instead of python sorting.

2017-02-15 17:15 UTC, youralien commented
This was the commit in Traffic Intelligence this depends on, fyi:

https://bitbucket.org/santosfamilyfoundation/trafficintelligence/pull-requests/3/limit-and-order-near-miss-by-severity/diff

2017-02-15 17:16 UTC, merged