WIP: Compare speeds
santosfamilyfoundation/TrafficCloud pull request #99
Opened 2017-04-23 16:23 UTC by youralien

compareSpeeds graphs

![comparepercentiles_harvey hardware j 19 00 - 20 00_harvey hardware j 10 00 - 11 00](https://cloud.githubusercontent.com/assets/5459644/25315221/b5ad6674-281f-11e7-8618-ff4dfe8bf994.jpg)

2017-04-24 01:15 UTC, segerphilip approved these changes
Graphs for speed comparisons look more understandable, code looks good as well as long as tested 👍

2017-04-25 17:44 UTC, dcelik requested changes
Looks like a good addition to our visualization codebase.

2017-04-25 17:44 UTC, dcelik commented on app/handlers/baseHandler.py
> +                ret_val = self.get_arguments(arg_name)
Let remove the print statements, but good catch.

2017-04-25 17:44 UTC, dcelik commented on app/handlers/compareSpeeds.py
> +import json
Do you need the JSON and traceback imports?

2017-04-25 17:44 UTC, dcelik commented on app/handlers/compareSpeeds.py
> +                            'attachment; filename=velocityPDF.jpg')
filename should be the image_filename from above

2017-04-25 17:44 UTC, dcelik commented on app/handlers/compareSpeeds.py
> +            self.finish("Create Speed Distribution")
Don't pass back any text in the finish, we should just call finish()

2017-04-25 17:44 UTC, dcelik commented on app/handlers/createSpeedDistribution.py
> +        if status_dict[Status.Type.OBJECT_TRACKING] != Status.Flag.COMPLETE:
Need to modify API docs to reflect this change.

2017-04-26 15:40 UTC, youralien commented on app/handlers/baseHandler.py
> +                ret_val = self.get_arguments(arg_name)
Removed in following commit

2017-04-26 18:31 UTC, youralien commented on app/handlers/createSpeedDistribution.py
> +        if status_dict[Status.Type.OBJECT_TRACKING] != Status.Flag.COMPLETE:
Changed!

2017-04-26 18:46 UTC, dcelik approved these changes

2017-04-26 19:04 UTC, merged